
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT"
export const SELLER_LOGIN = "SELLER_LOGIN";
export const SELLER_LOGOUT = "SELLER_LOGOUT";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";


//customer payment
export const GET_PAYMENT_DETAILS = "GET_PAYMENT_DETAILS";

export const CUSTOMER_GET_PRODUCTS = "CUSTOMER_GET_PRODUCTS";
export const CUSTOMER_GET_REVIEWS_FOR_PRODUCT = "CUSTOMER_GET_REVIEWS_FOR_PRODUCT";
export const CUSTOMER_ADD_REVIEW = "CUSTOMER_ADD_REVIEW";
export const GET_CART = "GET_CART";

export const SELLER_GET_PRODUCTS = "SELLER_GET_PRODUCTS";
export const SELLER_ADD_PRODUCT = "SELLER_ADD_PRODUCT";
export const SELLER_UPDATE_PRODUCT = "SELLER_UPDATE_PRODUCT";
export const SELLER_DELETE_PRODUCT = "SELLER_DELETE_PRODUCT";

export const UPDATE_CART = "UPDATE_CART";
export const GET_ORDERS = "GET_ORDERS";
export const ADD_PAYMENT_DETAILS = "ADD_PAYMENT_DETAILS";
export const GET_PRODUCT = "GET_PRODUCT";
export const SELLER_GET_ORDERS = "SELLER_GET_ORDERS"

export const FETCH_CUSTOMER_PROFILE = "FETCH_CUSTOMER_PROFILE";
export const SAVE_ADDRESS_DETAILS_TO_STORE = "SAVE_ADDRESS_DETAILS_TO_STORE";
export const SAVE_NAMEPIC_DETAILS_TO_STORE = "SAVE_NAMEPIC_DETAILS_TO_STORE"; 
export const SAVE_PAYMENT_DETAILS_TO_STORE = "SAVE_PAYMENT_DETAILS_TO_STORE";
export const EDIT_ADDRESS_DETAILS_TO_STORE = "EDIT_ADDRESS_DETAILS_TO_STORE";
export const DELETE_CUSTOMER_PAYEMET = "DELETE_CUSTOMER_PAYEMET";
export const UPDATE_CUSTOMER_PAYMENT = "UPDATE_CUSTOMER_PAYMENT";

export const UPDATE_SELLER_ADDRESS = "UPDATE_SELLER_ADDRESS";
export const FETCH_SELLER_PROFILE = "FETCH_SELLER_PROFILE";
export const UPDAT_SELLER_NAMPIC = "UPDAT_SELLER_NAMPIC";

export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
