
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT"
export const SELLER_LOGIN = "SELLER_LOGIN";
export const SELLER_LOGOUT = "SELLER_LOGOUT";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
